### ISSUE TITLE
Error when creating tables

### ISSUE THREAD

**Issue by tonydspaniard** [betaglop/e-venement#1]
Here the error: 

```
SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT 
column 'campaign' used in key specification without a key length. 
Failing Query: "CREATE TABLE web_origin (id BIGINT AUTO_INCREMENT, 
sf_guard_user_id BIGINT, automatic TINYINT(1) DEFAULT '0' NOT NULL, 
first_page TEXT NOT NULL, ipaddress VARCHAR(40) NOT NULL, 
referer TEXT, campaign TEXT, transaction_id BIGINT NOT NULL, 
user_agent TEXT NOT NULL, created_at DATETIME NOT NULL, 
updated_at DATETIME NOT NULL, version BIGINT, 
INDEX weborigin_updated_at_idx_idx (updated_at), 
INDEX weborigin_created_at_idx_idx (created_at), 
INDEX web_origin_com_idx_idx (campaign), 
INDEX web_origin_referer_idx_idx (referer), 
INDEX web_origin_first_page_idx_idx (first_page),
 INDEX sf_guard_user_id_idx (sf_guard_user_id), 
INDEX transaction_id_idx (transaction_id), 
PRIMARY KEY(id)) ENGINE = INNODB". 
Failing Query: CREATE TABLE web_origin (id BIGINT AUTO_INCREMENT, 
sf_guard_user_id BIGINT, automatic TINYINT(1) DEFAULT '0' NOT NULL, 
first_page TEXT NOT NULL, ipaddress VARCHAR(40) NOT NULL, referer TEXT, 
campaign TEXT, transaction_id BIGINT NOT NULL, user_agent TEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, version BIGINT, 
INDEX weborigin_updated_at_idx_idx (updated_at), 
NDEX weborigin_created_at_idx_idx (created_at), 
INDEX web_origin_com_idx_idx (campaign), 
INDEX web_origin_referer_idx_idx (referer), 
INDEX web_origin_first_page_idx_idx (first_page),
 INDEX sf_guard_user_id_idx (sf_guard_user_id), 
INDEX transaction_id_idx (transaction_id), 
PRIMARY KEY(id)) ENGINE = INNODB 
```

**Comment by betaglop** [comment]
Hi !
You seem to be using MySQL...
e-venement is tested only over PostgreSQL, even if it is based on Symfony1 and Sf1 supports MySQL.

But looking at the request, I cannot understand why it fails (even if I'm not a MySQL specialist, and far from it)...

Anyway, try using PostgreSQL and this happens again, we'll find out a solution to your issue.

**Comment by tonydspaniard** [comment]
Hi @betaglop, thank you for the prompt response. Yep, I am using mySql, modified the YAML to make it work and it does for the table creation not for the creation of indexes. I will investigate further. 

Thank you for your hard work. Its an inspiring project.

**Comment by tonydspaniard** [comment]
@betaglop  From the documentation:  

> BLOB and TEXT columns also can be indexed, but a prefix length must be given.

You can create an index to those field types but you must specify the key length: 

```sql
CREATE UNIQUE INDEX index_name ON misc_info (key(10));
```

**Comment by betaglop** [comment]
Ok thanks for this feedback tonydspaniard!
Have you found a solution within the YAML schema?

You can see that the english used in e-venement is quite poor and really imperfect... So any pull request is welcome to improve the software in this direction ;c)
