### ISSUE TITLE
Demo fixtures aren't up-to-date

### ISSUE THREAD

**Issue by pyrog** [betaglop/e-venement#10]
When following the installation guide http://www.e-venement.org/contribuer/installer/

```sh
./symfony doctrine:data-load --append data/fixtures/30-demo.yml
```

> doctrine  Loading data fixtures from "data/fixtures/30-demo.yml"
> Unknown record property / related component "latitude" on "Contact"  
>

**Comment by betaglop** [comment]
commit f5e8eae
commit 8a923fe

are closing this issue.
thanks for your contribution pyrog.
