### ISSUE TITLE
Error 500 when editing a contact

### ISSUE THREAD

**Issue by pyrog** [betaglop/e-venement#12]
http://127.0.0.1/rp_dev.php/contact/180/edit.html

> 500 | Internal Server Error | Doctrine_Query_Exception
> Unknown column name

## Note:
there is no `apps/rp/config/app.yml` file.

Copying `apps/rp/config/app.yml.template` to `apps/rp/config/app.yml` fixed this issue

**Comment by betaglop** [comment]
This is not an issue anymore, but a strategical choice accepting or not this pull request... ;)

**Comment by betaglop** [comment]
accepted
