### ISSUE TITLE
Exeption when showing customer profile

### ISSUE THREAD

**Issue by PapsOu** [betaglop/e-venement#281]
I've got this exception in logs when attempting to get customer informations :

```apache
[Mon May 29 09:14:39 2017] [error] [client X.X.X.X] Action "api/v2" does not exist., referer: http://localhost/front-online-choice/?/events
[Mon May 29 09:14:39 2017] [error] [client X.X.X.X] PHP Fatal error:  Uncaught exception 'sfStopException' in /var/www/DEV_SERVER/lib/vendor/externals/symfony1/lib/filter/sfBasicSecurityFilter.class.php:96\nStack trace:\n#0 /var/www/DEV_SERVER/lib/vendor/externals/symfony1/lib/filter/sfBasicSecurityFilter.class.php(55): sfBasicSecurityFilter->forwardToLoginAction()\n#1 /tmp/DEV_SERVER-7f589aac5174670ca286f93d71e4826a/cache/tck/prod/config/config_core_compile.yml.php(1031): sfBasicSecurityFilter->execute(Object(sfFilterChain))\n#2 /tmp/DEV_SERVER-7f589aac5174670ca286f93d71e4826a/cache/tck/prod/config/config_core_compile.yml.php(995): sfFilterChain->execute()\n#3 /tmp/DEV_SERVER-7f589aac5174670ca286f93d71e4826a/cache/tck/prod/config/config_core_compile.yml.php(1031): sfRenderingFilter->execute(Object(sfFilterChain))\n#4 /tmp/DEV_SERVER-7f589aac5174670ca286f93d71e4826a/cache/tck/prod/config/config_core_compile.yml.php(665): sfFilterChain->execute()\n#5 /var/www/DEV_SERVER/lib/v in /var/www/DEV_SERVER/lib/vendor/externals/symfony1/lib/filter/sfBasicSecurityFilter.class.php on line 96, referer: http://localhost/front-online-choice/?/events
```

The API return empty response (because of Exception) but it should return serialized customer informations

**Comment by betaglop** [comment]
This is linked to the issue related to the relation between OcToken and OcTransaction... The Doctrine property "```foreignType: one```" might not be correctly applied in ```lib/model/doctrine/liOnlineChoicesPlugin/base/```... It needs a ```rm -rf lib/model/doctrine/liOnlineChoicesPlugin/base/``` and a ```./symfony doctrine:build-model``` (+ forms + filters).

Now, that said, the correction in the source code of this ```foreignType: one``` should have been done badly. I'll give an update here ASAP.

**Comment by betaglop** [comment]
This issue should go into the plugin itself... This commit should solve it: https://github.com/betaglop/liOnlineChoicesPlugin/commit/b1176f5f30b7986707c3f31e19f270ba36516e38

If so, can I let you close the issue?

**Comment by PapsOu** [comment]
Your fix solve the issue, thanks
