### ISSUE TITLE
Impossibilité d'accéder aux stats (test Issue Ju)

### ISSUE THREAD

**Issue by 3eetage-jb** [betaglop/e-venement#3]
Je ne peux pas accéder aux stats

![capture d ecran 2015-08-24 a 16 26 28](https://cloud.githubusercontent.com/assets/14178627/9736154/ed9c54cc-563f-11e5-9fe1-20d5339e8878.png)

**Comment by betaglop** [comment]
Tu as cliqué sur CTRL+CLICK ou CLICK-MILIEU ou encore ACTION+CLICK sur le bouton "rafraîchir" des statistiques d'une manifestation. Ce n'est pas une action attendue, et elle ne peut être "attrappée" par e-venement pour la prévenir.
Ce bouton doit être cliqué "normalement" avec un CLICK-GAUCHE.

**Comment by 3eetage-jb** [comment]
Désolée, mais j'ai cliqué sur gauche. D'ailleurs je viens de le refaire et c'est la même chose. Idem sur la session de Samuel.

**Comment by betaglop** [comment]
ok compris et corrigé (y compris sur votre plateforme directement).
cf. commit dae89cc3b7df066a18da2a344956bd63b1b3e42c
