### ISSUE TITLE
New evenement - version 2.8.5

### ISSUE THREAD

**Issue by willylambert** [betaglop/e-venement#4]
On version 2.8.5, insertion of a new event failed with the following error:
`SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character(2), referer: http://xx.xx.xx.xx/event.php/event/new.html`

Values used are: 
nom (fr) = test
Méta-évenement : Saison 2014

**Comment by betaglop** [comment]
Hi,

Can you please reproduce this bug in a _dev environment ? e.g. http://xx.xx.xx.xx/event_dev.php/event/new.html (modifying the file web/event_dev.php to your needs)
Then copy/past the details of the raised exception...

We have never seen this kind of exception.
Thanks in advance,

**Comment by willylambert** [comment]
this error seems to be related to translation:

    ERROR:  value too long for type character(2)
    STATEMENT:  INSERT INTO event_translation (id, lang, name, short_name, subtitle, description,     'extradesc, extraspec) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)

By default the event form ask for translation in fr/bzh/en, but this is the only form asking for this. I'm able to create metaevent, place, ressources, etc. without any issue - but they do not ask for bzh/en translations.

![image](https://cloud.githubusercontent.com/assets/216868/9993698/5ad1fe32-6079-11e5-8f34-3ba67d2db25c.png)

I've setup an EC2 instance if you want to test : http://52.19.236.162/ 
login/passwd : demo/demo (event_dev.php is enabled)




Thanks for your help !

**Comment by betaglop** [comment]
ok I understand now...
a mistake was present in the config/project.yml.template:

project:
  internals:
    cultures:
      fr: Français
      en: English
      bzh: Breizhoneg

should be:

project:
  internals:
    cultures:
      fr: Français
      en: English
      br: Breizhoneg

I propose or to correct bzh -> br or to remove the unused languages in this configuration file.
Then everything will be in working order...

Corrections in the commits e5bd84a (v2.8) and b62851e (v2.9)

**Comment by willylambert** [comment]
Thanks, it works !
