### ISSUE TITLE
Mauvais liens de voisinage

### ISSUE THREAD

**Issue by 3eetage-jb** [betaglop/e-venement#5]
1/ Des liens de voisinage non voulus (croisés sur les extrémités des rangs) apparaissent.
2/ Il est impossible de les faire disparaitre en cliquant sur les liens comme il était possible de le faire précédemment
![capture d ecran 2015-09-14 a 20 21 03](https://cloud.githubusercontent.com/assets/14178627/9857979/27abe0e6-5b1e-11e5-8770-0157a757bfa7.png)
 
(Exemple pris sur la Jauge PA Cat 1 du Palais d'Auron)

**Comment by betaglop** [comment]
Bonjour,
Même si ce n'est pas très user-friendly, la fonctionnalité permettant de définir et de supprimer "un par un" les liens est toujours fonctionnelle.
Graphiquement le bug a été corrigée sur la future version 2.9, et vous êtes sur la 2.8.

Nous venons de faire le backport et, en faisant la mise à jour sur le serveur et en vidant le cache du navigateur, vous devriez pouvoir supprimer graphiquement ces liens "en trop".

commit: fd53432c7f70c7b9a4816ef1c128dd5782f7af4e
