### ISSUE TITLE
Mauvaise attribution des places dans un hold

### ISSUE THREAD

**Issue by 3eetage-jb** [betaglop/e-venement#6]
Lorsqu'on essaie d'ajouter une nouvelle opération dans un hold, l'attribution des places ne se fait pas correctement. Les gens d'une même opération sont placés un fauteuil sur deux (au lieu d'être sur des sièges contigus).

![capture d ecran 2015-09-14 a 20 28 24](https://cloud.githubusercontent.com/assets/14178627/9858163/627f4266-5b1f-11e5-9d66-5cd5ee00c5da.png)
 (exemple pris sur le hold FA16 invits, opération #21721)

**Comment by betaglop** [comment]
Bonjour,
Je ne comprends pas l'opération qui est en oeuvre ici ? S'agit-il d'une opération de placement automatisé des retenues ?

Si oui, je viens de vérifier votre plan, et le voisinage est en vrac. Je m'explique: si on regarde bien les liens, ils se font d'une place sur deux, comme si il s'agissait d'une place où les impairs était à gauche, et les pairs à droite ; où la place A3 était entre la A1 et la A5.
Or votre salle est numérotée de gauche à droite avec des sauts de 1, donc la place A3 est entre la A2 et la A4.
Il s'agit donc de mieux définir votre voisinage... Nous avons ajouté un texte d'aide pour préciser le rôle de la case à cocher "places contigües"...

**Comment by 3eetage-jb** [comment]
Ok. Du coup, avec la correction du bug sur les voisinages (enfin sur l'impossibilité de supprimer les liens + rappel sur la case "places contigues"), les conséquences sur les holds n'existent plus.
