### ISSUE TITLE
Mauvaise attribution des tarifs en vente en ligne

### ISSUE THREAD

**Issue by 3eetage-jb** [betaglop/e-venement#7]
Alors que le tableau croisé de la manifestation est bien renseigné et que les autorisations des tarifs sont correctement attribués, le store rend disponible des tarifs

1/ faux
2/ non disponible pour la catégorie de place sélectionnée

![capture d ecran 2015-08-25 a 14 01 23](https://cloud.githubusercontent.com/assets/14178627/9858235/db5e7abc-5b1f-11e5-82e1-ff932bcf8b8f.png)

(Exemple pris sur la manifestation FADOP-chapitre 2)

**Comment by betaglop** [comment]
Impossible de reproduire le bug.
De plus, votre instance de test a été mise à jour avec les données de production pour des contraintes de temps. Je crains que ce bug ne doive être reproduit pour pouvoir être corrigé.

**Comment by 3eetage-jb** [comment]
En se rendant sur store.3e-etage.com et en cliquant sur la seule manifestation existante, j'obtiens le plan en PJ avec des tarifs qui ne correspondent pas au tableau croisé (PJ 2)  : les tarifs non attribués à une jauge apparaissent à 0€ au lieu de ne pas apparaitre du tout. 

![capture d ecran 2015-09-21 a 17 48 45](https://cloud.githubusercontent.com/assets/14178627/9996812/28ce8a44-6089-11e5-9c78-d460b8693ed3.png)
![capture d ecran 2015-09-21 a 17 46 02](https://cloud.githubusercontent.com/assets/14178627/9996817/309e7342-6089-11e5-95cf-7dc2936ca5ae.png)

**Comment by betaglop** [comment]
ok c'est "tout à fait normal": vous êtes les premiers à avoir demandé à avoir des tarifs par "jauge". actuellement vous êtes les seuls à l'utiliser de manière exclusive (d'autres les utilisent, mais associés aux tarifs par manifestation). du coup des tarifs existaient sur la manifestation, mais n'étaient pas visibles sur votre configuration.

j'ai remis à plat à la fois la configuration de cette manifestation sur ce point précis, et le code pour éviter que vous ne soyez à nouveau ennuyés.

par ailleurs, j'ai remarqué une requête DB très très lente sur votre instance, nous allons nous pencher sur la raison de cette lenteur dans les jours à venir.
